export const LEDSTRIP_RGBW_BIT = 0x01;
export const LEDSTRIP_SET_LEDS_UPDATE_BIT = 0x02;

export default {
	SET_LEDS_RGB: 0x00,
	SET_LEDS_RGBW: 0x01,
	SET_LEDS_RGB_UPDATE: 0x02,
	SET_LEDS_RGBW_UPDATE: 0x03,
	FILL_RGB: 0x04,
	FILL_RGBW: 0x05,
	UPDATE_DISPLAY: 0x06
} as const;
